Fix `Basic` header authorization
florisbreggeman/das pull request #5
Opened 2023-08-16 11:21 UTC by Rafaeltheraven

As discussed here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization#basic_authentication the client+secret encoded in an `Authorization: Basic` header are base64 decoded, however, DAS never decodes this and thus will say that the secret is incorrect. This simple commit fixes it.

2023-08-16 15:37 UTC, notinecrafter requested changes

2023-08-16 15:51 UTC, florisbreggeman commented
Should this not use Base.decode64! (with the exclamation mark?)

Base.decode64 will return {:ok, "string"}, whereas Base.decode64! will return a string...

2023-08-16 17:55 UTC, Rafaeltheraven commented
Ah you're right, my elixir skills leave much to be desired. Fixed.

2025-01-01 16:10 UTC, florisbreggeman commented
Already fixed in https://github.com/florisbreggeman/das/pull/7

2025-01-01 16:11 UTC, closed without merging